#!/usr/bin/env python3
# Mainly generated by the use of AI

"""
Enter an interactive shell in kernel instance 1 (ghost).

Must run as root.  Requires a kernel with CONFIG_KERNEL_INSTANCE and
/proc/ki_ctrl that reports errors if migration fails (older kernels
silently ignored unknown PIDs — children then stayed on instance 0 and
remained visible from the boot instance via ps/top).
"""
from __future__ import annotations

import os
import sys


def _read_ki_id() -> str:
    try:
        with open("/proc/ki_id", encoding="ascii") as f:
            return f.read().strip()
    except OSError as e:
        print(f"Error: reading /proc/ki_id: {e}", file=sys.stderr)
        sys.exit(1)


def run_ghost_shell() -> None:
    if os.geteuid() != 0:
        print("Error: Root required (sudo).", file=sys.stderr)
        sys.exit(1)

    pid = os.getpid()
    line = f"{pid} 1\n"
    try:
        with open("/proc/ki_ctrl", "w", encoding="ascii") as f:
            f.write(line)
            f.flush()
    except FileNotFoundError:
        print("Error: /proc/ki_ctrl missing (CONFIG_KERNEL_INSTANCE?)", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f"Error: ki_ctrl: {e}", file=sys.stderr)
        print(
            "Hint: PID not found (-ESRCH) or wrong PID-Namespace-Pair.",
            file=sys.stderr,
        )
        sys.exit(1)

    kid = _read_ki_id()
    if kid != "1":
        print(
            f"Error: Migration failed — /proc/ki_id is '{kid}', expected '1'.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"--- SUPERVISOR: PID {pid} is in instance 1 (ghost) ---")
    print("Shell started; Child processes (e.g. top) inherit task->ki from parent process.")
    os.environ["PS1"] = "SHELL-I1 # "
    os.execl("/bin/bash", "bash", "-i")


if __name__ == "__main__":
    run_ghost_shell()
