#!/usr/bin/env bash
#
# Load a raw memory image into the ghost cage from the boot instance.
# Requires: boot may access ghost cage via /dev/mem; cage >= dump.
#
# Usage:
#   sudo ./load_dump_to_ghost_cage.sh /path/to/vm.dump
#
# Mainly generated by the use of AI
set -euo pipefail

DUMP="${1:?usage: $0 <dump-file>}"
[[ -r "/proc/ki_layout" ]] || { echo "no /proc/ki_layout"; exit 1; }

eval "$(grep -E '^(cage_start|cage_size)=' /proc/ki_layout | sed 's/^/KI_/')"

: "${KI_cage_start:?}"
: "${KI_cage_size:?}"

DUMP_LEN=$(stat -c '%s' "$DUMP")

if (( DUMP_LEN > KI_cage_size )); then
	NEED_MIB=$(( (DUMP_LEN + 1048576 - 1) / 1048576 ))
	CAGE_MIB=$(( (KI_cage_size + 1048576 - 1) / 1048576 ))
	echo "Dump (${DUMP_LEN} B) exceeds cage (${KI_cage_size} B, ~${CAGE_MIB} MiB)." >&2
	echo "Need cage_size >= ${DUMP_LEN} B (~${NEED_MIB} MiB)." >&2
	echo "Fix: enlarge guest RAM or increase the default ghost_ki_mem_size in init/main.c (need >= ${NEED_MIB} MiB)." >&2
	echo "      The kernel also caps the window so (cage + 1 GiB) fits in visible DRAM (see init/main.c boot_keep)." >&2
	exit 1
fi

PHYS=$KI_cage_start
echo "cage_start=$KI_cage_start cage_size=$KI_cage_size"
echo "phys_start=0x$(printf '%x' "$PHYS") copy_len=$DUMP_LEN"

[[ -c /dev/mem ]] || { echo "/dev/mem missing"; exit 1; }

dd if="$DUMP" of=/dev/mem bs=1M seek=$((PHYS / 1048576)) conv=notrunc

echo "Done."
