#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
#
# tools/kernel_instance/memory_marker.py
#
# Plant a known byte pattern in the caller's heap, pin it with mlock() and
# self-detach so the invoking (interactive) shell returns immediately. The
# marker process keeps running in the background and holds the page until it
# is killed.
#
# Typical workflow inside a ghost shell (SHELL-I1):
#
#     $ sudo python3 memory_marker.py           # marker process daemonises
#     [marker] pid=4711 virt=0x7fbc... phys=0x17b3a8cc0 in_cage=yes
#
#     # now back to the shell; dump / inspect as you like, e.g.
#     $ sudo dd if=/proc/kcore bs=1M count=...
#
#     # when done:
#     $ sudo python3 memory_marker.py --stop
#
# Flags:
#     --stop             kill the last-started marker (reads /tmp/ki_marker.pid)
#     --foreground       stay attached (old behaviour, blocks the shell)
#     --marker STRING    custom marker bytes (default: INSTANCE_SECRET_MARKER)
#     --pidfile PATH     PID file (default: /tmp/ki_marker.pid)

# Mainly generated by the use of AI
import argparse
import ctypes
import ctypes.util
import os
import signal
import struct
import sys
import time

DEFAULT_MARKER = "INSTANCE_0_SECRET_MARKER"
DEFAULT_PIDFILE = "/tmp/ki_marker.pid"


def virt_to_phys(virt_addr: int) -> int | None:
    """Return the physical address backing *virt_addr* for the caller."""
    page_size = os.sysconf("SC_PAGESIZE")
    page_index = virt_addr // page_size
    page_offset = virt_addr % page_size
    with open(f"/proc/{os.getpid()}/pagemap", "rb") as f:
        f.seek(page_index * 8)
        entry = int.from_bytes(f.read(8), "little")
    if not (entry & (1 << 63)):
        return None
    pfn = entry & ((1 << 55) - 1)
    if pfn == 0:
        return None
    return pfn * page_size + page_offset


def read_cage_bounds() -> tuple[int, int] | None:
    """Parse /proc/ki_layout and return (cage_start, cage_size)."""
    try:
        with open("/proc/ki_layout") as f:
            text = f.read()
    except FileNotFoundError:
        return None

    fields: dict[str, int] = {}
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        try:
            fields[key.strip()] = int(value.strip(), 0)
        except ValueError:
            pass

    if "cage_start" in fields and "cage_size" in fields and fields["cage_size"]:
        return fields["cage_start"], fields["cage_size"]
    return None


def my_ki_id() -> str:
    """Return the ki_id of the caller.

    /proc/ki_id is the single-entry, self-scoped interface exported by
    kernel/kernel_instance.c (ki_id_show reads current_ki()->id), so only
    reading it from the current process yields a meaningful value. There
    is no per-pid variant.
    """
    try:
        with open("/proc/ki_id") as f:
            return f.read().strip()
    except FileNotFoundError:
        return "?"


def mlock_buffer(addr: int, size: int) -> None:
    """Lock the buffer into RAM so it cannot be swapped out. Best-effort."""
    libc = ctypes.CDLL(ctypes.util.find_library("c") or "libc.so.6",
                       use_errno=True)
    if libc.mlock(ctypes.c_void_p(addr), ctypes.c_size_t(size)) != 0:
        err = ctypes.get_errno()
        print(f"[marker] warning: mlock() failed: {os.strerror(err)}",
              file=sys.stderr)


def write_pidfile(path: str) -> None:
    with open(path, "w") as f:
        f.write(f"{os.getpid()}\n")


def cmd_stop(pidfile: str) -> int:
    try:
        with open(pidfile) as f:
            pid = int(f.read().strip())
    except FileNotFoundError:
        print(f"[marker] no pidfile at {pidfile}", file=sys.stderr)
        return 1
    except ValueError:
        print(f"[marker] pidfile {pidfile} is corrupt", file=sys.stderr)
        return 1

    try:
        os.kill(pid, signal.SIGTERM)
        print(f"[marker] SIGTERM sent to pid {pid}")
    except ProcessLookupError:
        print(f"[marker] pid {pid} already gone")
    except PermissionError:
        print(f"[marker] no permission to kill {pid} (run as root?)",
              file=sys.stderr)
        return 1

    try:
        os.unlink(pidfile)
    except FileNotFoundError:
        pass
    return 0


def plant_marker(marker: bytes) -> tuple[int, int]:
    """Allocate a buffer, write *marker* into it, pin and report (virt, size)."""
    # Use a fresh anonymous mapping instead of ctypes' Python-heap buffer:
    # that guarantees we own the page and no earlier pre-fault on the glibc
    # arena can serve a page allocated *before* the task got tagged.
    import mmap
    size = max(4096, len(marker) + 1)
    m = mmap.mmap(-1, size,
                  flags=mmap.MAP_PRIVATE | mmap.MAP_ANONYMOUS,
                  prot=mmap.PROT_READ | mmap.PROT_WRITE)
    m.write(marker + b"\x00")
    virt = ctypes.addressof(ctypes.c_char.from_buffer(m))
    mlock_buffer(virt, size)
    # Keep a reference so Python doesn't GC the mmap object.
    plant_marker._keepalive = m  # type: ignore[attr-defined]
    return virt, size


def daemonise() -> None:
    """Classic two-fork detach. The original shell gets its prompt back."""
    if os.fork() != 0:
        # Parent of fork 1 -- exit so the shell returns.
        os._exit(0)
    os.setsid()
    if os.fork() != 0:
        os._exit(0)
    # Redirect stdio so the background process doesn't accidentally write
    # into the user's tty.
    devnull = os.open(os.devnull, os.O_RDWR)
    for fd in (0, 1, 2):
        os.dup2(devnull, fd)
    os.close(devnull)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--marker", default=DEFAULT_MARKER)
    ap.add_argument("--pidfile", default=DEFAULT_PIDFILE)
    ap.add_argument("--foreground", action="store_true",
                    help="do not detach, block the shell (debug)")
    ap.add_argument("--stop", action="store_true",
                    help="kill the previously started marker")
    args = ap.parse_args()

    if args.stop:
        return cmd_stop(args.pidfile)

    marker_bytes = args.marker.encode()
    virt, size = plant_marker(marker_bytes)
    phys = virt_to_phys(virt)

    cage = read_cage_bounds()
    in_cage = "unknown"
    if cage and phys is not None:
        base, bsize = cage
        in_cage = "yes" if base <= phys < base + bsize else "no"

    pid_before = os.getpid()
    ki_id_before = my_ki_id()

    print(f"[marker] marker    = {args.marker!r}")
    print(f"[marker] pid       = {pid_before}")
    print(f"[marker] ki_id     = {ki_id_before}")
    print(f"[marker] virt      = {hex(virt)}")
    print(f"[marker] phys      = "
          f"{hex(phys) if phys is not None else '<not present>'}")
    if cage:
        base, bsize = cage
        print(f"[marker] cage      = [{hex(base)} .. {hex(base + bsize)})"
              f"  ({bsize >> 20} MiB)")
    else:
        print("[marker] cage      = /proc/ki_layout unavailable")
    print(f"[marker] in_cage   = {in_cage}")

    if args.foreground:
        print("[marker] holding memory in foreground, Ctrl-C to exit")
        try:
            signal.pause()
        except KeyboardInterrupt:
            return 0
        return 0

    # Background mode: detach so the invoking shell can keep working.
    sys.stdout.flush()
    sys.stderr.flush()
    daemonise()
    # After daemonise() we're in a fresh session. Re-mlock in case the child
    # inherited the lock but the kernel dropped it across setsid (it doesn't,
    # but this is cheap and defensive). Then just sleep forever.
    mlock_buffer(virt, size)
    write_pidfile(args.pidfile)

    def _exit_handler(signum, _frame):
        try:
            os.unlink(args.pidfile)
        except FileNotFoundError:
            pass
        sys.exit(0)

    signal.signal(signal.SIGTERM, _exit_handler)
    signal.signal(signal.SIGINT, _exit_handler)

    while True:
        time.sleep(3600)


if __name__ == "__main__":
    sys.exit(main())
