#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# tools/kernel_instance/verify_ghost_process_isolation.sh
#
# Smoke-test for kernel-instance tagging + fork inheritance.
# /proc is NOT filtered by instance: boot and ghost share the same task list.
# Memory routing (page allocator, ghost cage) is orthogonal to this script.
#
#   1. Spawn a child bash, tag it instance 1 via /proc/ki_ctrl.
#   2. Child forks a marker (sleep) that inherits the ghost instance.
#   3. Boot instance (0) must still see ghost PIDs in /proc, readdir, and ps.
#   4. Harness re-tagged to instance 1 must still see the marker.
#
# Exit 0 iff every assertion holds.  Must run as root to write /proc/ki_ctrl.

# Mainly generated by the use of AI

set -u

green='\033[32m'; red='\033[31m'; yellow='\033[33m'; bold='\033[1m'; rst='\033[0m'
fail=0; passc=0

pass() { printf "${green}[PASS]${rst} %s\n" "$*"; passc=$((passc+1)); }
warn() { printf "${yellow}[WARN]${rst} %s\n" "$*"; }
err()  { printf "${red}[FAIL]${rst} %s\n" "$*"; fail=$((fail+1)); }
info() { printf "${bold}[INFO]${rst} %s\n" "$*"; }

if [[ $(id -u) -ne 0 ]]; then
	err "must run as root (needs /proc/ki_ctrl)"; exit 1
fi
if [[ ! -w /proc/ki_ctrl || ! -r /proc/ki_id ]]; then
	err "/proc/ki_{ctrl,id} missing -- CONFIG_KERNEL_INSTANCE off?"; exit 1
fi

MARKER_COMM="ki_probe_mrkr"  # max 15 chars (TASK_COMM_LEN); avoid pgrep/comm edge cases
TMPDIR=$(mktemp -d)
cleanup() {
	echo "$$ 0" > /proc/ki_ctrl 2>/dev/null || true
	[[ -n "${MPID:-}"      ]] && kill "$MPID"      2>/dev/null || true
	[[ -n "${GHOST_PID:-}" ]] && kill "$GHOST_PID" 2>/dev/null || true
	rm -rf "$TMPDIR"
}
trap cleanup EXIT

# ------------------------------------------------------------------
# Stage 1: spawn a child shell, tag it ghost, spawn the marker in it.
# ------------------------------------------------------------------
info "spawning child bash (will be tagged instance 1)"

(
	while [[ ! -e "$TMPDIR/go_fork" ]]; do sleep 0.05; done
	cat /proc/ki_id > "$TMPDIR/ghost_bash.ki_id" 2>/dev/null || \
		echo "?" > "$TMPDIR/ghost_bash.ki_id"
	if [[ -x /usr/bin/sleep ]]; then
		exec -a "$MARKER_COMM" /usr/bin/sleep 3600 &
	else
		exec -a "$MARKER_COMM" sleep 3600 &
	fi
	MPID=$!
	echo "$MPID" > "$TMPDIR/marker.pid"
	# Parent ki_id at fork time (child inherits task->ki in fork.c).
	cp "$TMPDIR/ghost_bash.ki_id" "$TMPDIR/marker.ki_id"
	wait "$MPID"
) &
GHOST_PID=$!
GBASH=$GHOST_PID
info "ghost bash PID = $GBASH"

echo "$GBASH 1" > /proc/ki_ctrl
: > "$TMPDIR/go_fork"

for _ in $(seq 1 100); do
	[[ -s "$TMPDIR/ghost_bash.ki_id" ]] && break
	sleep 0.05
done
[[ -s "$TMPDIR/ghost_bash.ki_id" ]] || \
	{ err "ghost bash did not report its ki_id"; exit 1; }

gid=$(cat "$TMPDIR/ghost_bash.ki_id")
if [[ "$gid" != "1" ]]; then
	err "failed to tag ghost bash (got ki_id=$gid)"; exit 1
fi
pass "ghost bash tagged: self-reported ki_id == 1"

for _ in $(seq 1 100); do
	[[ -s "$TMPDIR/marker.pid" && -s "$TMPDIR/marker.ki_id" ]] && break
	sleep 0.05
done
[[ -s "$TMPDIR/marker.pid" ]]    || { err "marker did not start"; exit 1; }
[[ -s "$TMPDIR/marker.ki_id" ]]  || { err "marker ki_id not captured"; exit 1; }

MPID=$(cat "$TMPDIR/marker.pid")
info "marker PID (should inherit ghost) = $MPID"

mid_from_ghost=$(cat "$TMPDIR/marker.ki_id")
if [[ "$mid_from_ghost" == "1" ]]; then
	pass "marker forked from ghost parent (parent ki_id was 1)"
else
	err "ghost parent ki_id was $mid_from_ghost at marker fork -- fork.c hook broken?"
fi

# ------------------------------------------------------------------
# Stage 2: boot instance sees ghost tasks in /proc (no hide filter).
# ------------------------------------------------------------------
info "probing /proc from boot instance (ghost PIDs remain visible)"

if [[ -e /proc/$MPID ]]; then
	pass "/proc/$MPID visible from boot"
else
	err "/proc/$MPID missing from boot"
fi

if [[ -e /proc/$GBASH ]]; then
	pass "/proc/$GBASH (ghost bash) visible from boot"
else
	err "/proc/$GBASH (ghost bash) missing from boot"
fi

if ls /proc 2>/dev/null | grep -qx "$MPID"; then
	pass "readdir(/proc) lists ghost marker $MPID"
else
	err "readdir(/proc) does not list ghost marker $MPID"
fi
if ls /proc 2>/dev/null | grep -qx "$GBASH"; then
	pass "readdir(/proc) lists ghost bash $GBASH"
else
	err "readdir(/proc) does not list ghost bash $GBASH"
fi

if ps -o pid= -p "$MPID" 2>/dev/null | grep -q "$MPID"; then
	pass "ps -p $MPID succeeds from boot"
else
	err "ps -p $MPID fails from boot"
fi

marker_comm=$(tr -d '\0\n' < "/proc/$MPID/comm" 2>/dev/null || true)
if [[ "$marker_comm" == "$MARKER_COMM" ]]; then
	pass "marker /proc/$MPID/comm is $MARKER_COMM"
elif kill -0 "$MPID" 2>/dev/null; then
	# pgrep -x matches comm literally; exec -a may still leave comm as "sleep"
	warn "marker comm is '${marker_comm:-?}' not '$MARKER_COMM' (exec -a quirk); process is alive"
	pass "marker PID $MPID running and visible from boot"
else
	err "marker PID $MPID not running (comm=${marker_comm:-?})"
fi

for f in status comm stat cmdline; do
	if cat /proc/$MPID/$f >/dev/null 2>&1; then
		pass "/proc/$MPID/$f readable from boot"
	else
		err "/proc/$MPID/$f not readable from boot"
	fi
done

if [[ -r /proc/1/comm ]]; then
	pass "control: /proc/1/comm still accessible from boot"
else
	err "control: /proc/1/comm unreadable -- something else is broken"
fi

# ------------------------------------------------------------------
# Step 3: ghost instance still sees its marker (symmetry).
# ------------------------------------------------------------------
info "probing /proc from ghost instance (re-tag harness)"

echo "$$ 1" > /proc/ki_ctrl

if [[ -e /proc/$MPID ]]; then
	pass "from ghost: /proc/$MPID visible"
else
	err "from ghost: /proc/$MPID NOT visible"
fi
if ps -o pid= -p "$MPID" 2>/dev/null | grep -q "$MPID"; then
	pass "from ghost: ps -p $MPID succeeds"
else
	err "from ghost: ps -p $MPID fails"
fi

echo "$$ 0" > /proc/ki_ctrl

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------
printf "\n${bold}Summary:${rst} %d passed, %d failed\n" "$passc" "$fail"
exit $(( fail > 0 ))
