#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# tools/kernel_instance/verify_ghost_isolation.sh
#
# End-to-end sanity check for ghost-cage isolation (memblock cage + gen_pool +
# page_alloc diversion + /dev/mem policy). Run from the boot instance as root:
#
#     sudo ./tools/kernel_instance/verify_ghost_isolation.sh
#
# Checks:
#   1. dmesg + /proc/ki_layout report a non-zero cage and gen_pool online
#   2. Ghost-tagged anon page lands in the cage; ghost /dev/mem cannot read outside cage
#
# Note: boot instance (id 0) may read the cage via /dev/mem (needed for dump load).

# Mainly generated by the use of AI

set -u

green='\033[32m'; red='\033[31m'; yellow='\033[33m'; bold='\033[1m'; rst='\033[0m'
fail=0
pass=0

pass() { printf "${green}[PASS]${rst} %s\n" "$*"; pass=$((pass+1)); }
warn() { printf "${yellow}[WARN]${rst} %s\n" "$*"; }
err()  { printf "${red}[FAIL]${rst} %s\n" "$*"; fail=$((fail+1)); }
info() { printf "${bold}[INFO]${rst} %s\n" "$*"; }

cleanup() {
	[[ -w /proc/ki_ctrl ]] && echo "$$ 0" > /proc/ki_ctrl 2>/dev/null || true
}
trap cleanup EXIT

if [[ $(id -u) -ne 0 ]]; then
	err "Must be run as root (needs dmesg and /dev/mem access)."
	exit 1
fi

if [[ ! -r /proc/ki_layout ]]; then
	err "/proc/ki_layout missing -- build with CONFIG_KERNEL_INSTANCE=y"
	exit 1
fi

################################################################################
# 1. dmesg + /proc/ki_layout: cage reserved and pool online
################################################################################
info "Parsing dmesg for KI log output ..."
DMESG=$(dmesg 2>/dev/null || journalctl -k --no-pager 2>/dev/null)

if [[ -z "$DMESG" ]]; then
	err "Could not collect kernel log (dmesg/journalctl empty)."
	exit 1
fi

if grep -q 'KI: ghost cage disabled' <<<"$DMESG"; then
	err "Cage was disabled at boot ($(grep 'KI: ghost cage disabled' <<<"$DMESG" | tail -n1 | sed 's/^[[:space:]]*//'))"
	exit 1
fi

ghost_line=$(grep -E 'KI: ghost physical cage' <<<"$DMESG" | tail -n 1)
if [[ -z "$ghost_line" ]]; then
	err "No 'KI: ghost physical cage' line in dmesg -- ki_compute_ghost_cage() did not run?"
	exit 1
fi
echo "    $ghost_line"

# Expected format:
#   KI: ghost physical cage [0x66800000 .. 0x76800000) (256 MiB) reserved
cage_base=$(grep -oE '\[0x[0-9a-fA-F]+' <<<"$ghost_line" | head -n1 | tr -d '[')
cage_end=$(grep -oE '\.\. 0x[0-9a-fA-F]+' <<<"$ghost_line" | head -n1 | awk '{print $2}')
cage_size_mib=$(grep -oE '\([0-9]+ MiB\)' <<<"$ghost_line" | head -n1 | grep -oE '[0-9]+')

if [[ -z "$cage_base" || -z "$cage_end" || -z "$cage_size_mib" ]]; then
	err "Failed to parse ghost cage offsets from dmesg line."
	exit 1
fi

cage_base_d=$(( cage_base ))
cage_end_d=$(( cage_end ))
cage_size_d=$(( cage_end_d - cage_base_d ))
info "Ghost cage physical range: $cage_base .. $cage_end ($cage_size_mib MiB = $cage_size_d bytes)"

grep -q 'KI: ghost page pool online' <<<"$DMESG" \
	&& pass "Ghost gen_pool initialised." \
	|| err  "Missing 'KI: ghost page pool online' -- kernel_instance_pool.c did not run."

eval "$(grep -E '^(cage_start|cage_size)=' /proc/ki_layout | sed 's/^/KI_/')"
if [[ -z "${KI_cage_start:-}" || -z "${KI_cage_size:-}" ]]; then
	err "/proc/ki_layout missing cage_start or cage_size."
elif (( KI_cage_size == 0 )); then
	err "/proc/ki_layout reports cage_size=0."
else
	pass "/proc/ki_layout exports non-zero cage (size=$KI_cage_size bytes)."
	# cage_start from %pa may be 0x-prefixed hex; compare numerically
	layout_base_d=$(( KI_cage_start ))
	if (( layout_base_d != cage_base_d || KI_cage_size != cage_size_d )); then
		warn "/proc/ki_layout ($KI_cage_start + $KI_cage_size) differs from dmesg range."
	fi
fi

################################################################################
# 2. Marker test: ghost anon page in cage + ghost /dev/mem restricted to cage.
################################################################################
info "Running marker test (ghost-tagged anon allocation) ..."

if [[ ! -w /proc/ki_ctrl ]]; then
	err "/proc/ki_ctrl missing -- cannot run marker test."
else
	marker_out=$(MARKER_BASE=$cage_base_d MARKER_END=$cage_end_d \
		python3 - <<'PY'
import ctypes, mmap, os, struct, sys

PAGE_SIZE = 4096

cage_base = int(os.environ["MARKER_BASE"])
cage_end  = int(os.environ["MARKER_END"])

with open("/proc/ki_ctrl", "w") as f:
    f.write(f"{os.getpid()} 1\n")

with open("/proc/ki_id") as f:
    if f.read().strip() != "1":
        print("ERROR: ki_id is not 1 after ki_ctrl", file=sys.stderr)
        sys.exit(4)

# Ghost must not read boot RAM via /dev/mem (outside the cage).
try:
    with open("/dev/mem", "rb", buffering=0) as mem:
        mem.seek(4096)
        mem.read(1)
    print("DEVMEM_OUTSIDE=allowed")
except OSError:
    print("DEVMEM_OUTSIDE=denied")

buf = mmap.mmap(-1, PAGE_SIZE, prot=mmap.PROT_READ | mmap.PROT_WRITE,
                flags=mmap.MAP_PRIVATE | mmap.MAP_ANONYMOUS)
buf[0:1] = b"x"
addr_va = ctypes.addressof(ctypes.c_char.from_buffer(buf))

with open("/proc/self/pagemap", "rb") as pm:
    pm.seek((addr_va // PAGE_SIZE) * 8)
    entry = struct.unpack("<Q", pm.read(8))[0]

if not (entry & (1 << 63)):
    print("ERROR: pagemap entry not present", file=sys.stderr)
    sys.exit(2)

pfn = entry & ((1 << 55) - 1)
phys = pfn * PAGE_SIZE
in_cage = cage_base <= phys < cage_end
print(f"PHYS=0x{phys:x} IN_CAGE={1 if in_cage else 0}")
sys.exit(0 if in_cage else 1)
PY
	)
	rc=$?
	echo "    $marker_out"
	case $rc in
		0)
			pass "Ghost anon page landed inside the cage."
			if grep -q 'DEVMEM_OUTSIDE=denied' <<<"$marker_out"; then
				pass "Ghost /dev/mem read outside cage denied."
			elif grep -q 'DEVMEM_OUTSIDE=allowed' <<<"$marker_out"; then
				err "Ghost /dev/mem could read outside cage -- ki_devmem_phys_range_allowed() broken."
			else
				warn "Ghost /dev/mem outside-cage probe inconclusive."
			fi
			;;
		1)
			err "Ghost anon page landed OUTSIDE the cage -- page_alloc diversion broken."
			;;
		2)
			warn "Pagemap entry for the marker was not present -- could not classify."
			;;
		4)
			err "ki_ctrl migration to instance 1 failed."
			;;
		*)
			err "Marker probe errored out (rc=$rc)."
			;;
	esac
fi

################################################################################
# Summary
################################################################################
printf "\n${bold}Summary:${rst} %d passed, %d failed\n" "$pass" "$fail"
if (( fail > 0 )); then
	exit 1
fi
info "Ghost cage isolation looks healthy on this boot."
info "Next: load a dump with tools/kernel_instance/load_dump_to_ghost_cage.sh"
